# -*- coding: utf-8 -*-
"""config

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xG4qwr2ifSvSg4oP_OviFJN4D-0vAQ8a
"""

# config.py

import os

# 프로젝트 기본 경로
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# 데이터 파일 경로
# 사용자는 '/data/kor_stocks.parquet' 경로에 주식 데이터를 위치시켜야 합니다.
DATA_PATH = os.path.join(BASE_DIR, 'data', 'kor_stocks.parquet')

# LLM 모델 설정
LLM_MODEL_NAME = "gpt-4-turbo"