# -*- coding: utf-8 -*-
"""idea_agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13gorx4jIDXbX9wmGISGKisx2O8ZteZNu
"""

# /agents/idea_agent.py

import json
import re
from clients.llm_client import LLMClient

class IdeaAgent:
    """
    시장 가설을 생성하고 개선하는 역할을 담당하는 에이전트.
    LLM을 사용하여 사용자의 초기 아이디어를 구조화된 가설로 변환하고,
    백테스팅 결과를 바탕으로 새로운 가설을 생성합니다.
    """
    def __init__(self, llm_client: LLMClient):
        """
        에이전트를 초기화합니다.

        Args:
            llm_client (LLMClient): LLM과 상호작용하기 위한 클라이언트.
        """
        self.llm_client = llm_client

    def generate_initial_hypothesis(self, initial_insight: str) -> dict:
        """
        사용자의 초기 아이디어를 기반으로 첫 번째 시장 가설을 생성합니다.

        Args:
            initial_insight (str): 시장에 대한 사용자의 초기 아이디어 또는 관찰.

        Returns:
            dict: 구조화된 시장 가설.
                  (예: {'knowledge', 'observation', 'justification', 'hypothesis', 'specification'})
        """
        system_prompt = """
        당신은 월스트리트의 저명한 퀀트 분석가입니다. 당신의 임무는 주어진 시장 인사이트를 바탕으로,
        검증 가능한 정량적 투자 가설을 체계적으로 수립하는 것입니다.
        결과는 반드시 다음의 5가지 요소를 포함하는 JSON 형식으로 응답해야 합니다.
        1. knowledge: 가설의 기반이 되는 금융 이론이나 시장 원리.
        2. observation: 현재 시장에서 관찰되는 구체적인 현상.
        3. justification: 관찰된 현상이 금융 이론에 의해 어떻게 설명될 수 있는지 논리적 근거.
        4. hypothesis: '만약 ~하다면, ~할 것이다' 형태의 명확하고 검증 가능한 가설.
        5. specification: 가설을 팩터로 구현할 때 고려해야 할 구체적인 조건이나 파라미터.
        JSON 응답 외의 다른 설명은 절대로 추가하지 마세요
        """
        user_prompt = f"다음 사용자 인사이트를 바탕으로 구조화된 투자 가설을 JSON 형식으로 생성해주세요:\n\n---\n{initial_insight}\n---"

        response_text = self.llm_client.generate_text(user_prompt, system_prompt)
        try:
            return json.loads(response_text)
        except json.JSONDecodeError:
            print("오류: LLM이 유효한 JSON 형식의 가설을 생성하지 못했습니다.")
            return {}

    except json.JSONDecodeError as e:
        print(f"오류: 추출된 텍스트가 유효한 JSON이 아닙니다. 오류: {e}")
        print("파싱 시도 텍스트:", match.group(0) if 'match' in locals() and match else "N/A")
        return {}

    def refine_hypothesis(self, previous_results: dict) -> dict:
        """
        이전 백테스팅 결과를 바탕으로 기존 가설을 개선하거나 새로운 가설을 생성합니다.

        Args:
            previous_results (dict): 이전 주기의 평가 결과 요약.
                                     (예: {'best_factor': ..., 'average_ic': ...})

        Returns:
            dict: 새롭게 생성되거나 개선된 구조화된 시장 가설.
        """
        system_prompt = """
        당신은 실패로부터 배우는 뛰어난 퀀트 전략가입니다.
        이전 투자 전략의 성과 보고서를 보고, 실패 원인을 분석한 뒤,
        이를 개선할 수 있는 새롭고 창의적인 투자 가설을 제시해야 합니다.
        결과는 이전과 동일하게 5가지 요소를 포함하는 JSON 형식으로 응답해야 합니다.
        """
        user_prompt = f"다음은 이전 투자 아이디어의 성과 요약입니다. 이 결과를 분석하고, 더 나은 성과를 낼 수 있는 새로운 투자 가설을 JSON 형식으로 제안해주세요:\n\n---\n{json.dumps(previous_results, indent=2, ensure_ascii=False)}\n---"

        response_text = self.llm_client.generate_text(user_prompt, system_prompt)
        try:
            return json.loads(response_text)
        except json.JSONDecodeError:
            print("오류: LLM이 유효한 JSON 형식의 개선된 가설을 생성하지 못했습니다.")
            return {}
